# Generated by Django 5.0.2 on 2024-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('company', 'Company')], max_length=10),
        ),
    ]
