# Generated by Django 5.0.2 on 2024-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='github_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(default='London, UK', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
