# Generated by Django 5.0.2 on 2024-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_client_github_url_client_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cv',
            field=models.FileField(upload_to='users/cvs/'),
        ),
    ]
