version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=fm_joblistings.settings.development
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    container_name: joblisting_app