# Generated by Django 5.0.2 on 2024-02-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('FE', 'Frontend'), ('FS', 'Fullstack'), ('BE', 'Backend')], max_length=2)),
                ('level', models.CharField(choices=[('J', 'Junior'), ('M', 'Midweight'), ('S', 'Senior')], default='J', max_length=1)),
                ('contract', models.CharField(choices=[('PT', 'Part Time'), ('FT', 'Full Time')], default='FT', max_length=2)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.PositiveBigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.company')),
                ('languages', models.ManyToManyField(to='job_portal.language')),
                ('tools', models.ManyToManyField(to='job_portal.tool')),
            ],
        ),
    ]
