# Generated by Django 5.0.2 on 2024-03-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_remove_job_is_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
