# Generated by Django 5.0.2 on 2024-09-03 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_job_benefits_job_description_job_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='svg_icon',
            field=models.FileField(blank=True, upload_to='job_portal/svg_icons/'),
        ),
        migrations.AddField(
            model_name='language',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
