# Generated by Django 5.0.4 on 2024-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0008_language_created_date_language_svg_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='svg_icon',
            field=models.FileField(blank=True, upload_to='job_portal/svg_icons/tools/'),
        ),
        migrations.AlterField(
            model_name='language',
            name='svg_icon',
            field=models.FileField(blank=True, upload_to='job_portal/svg_icons/languages/'),
        ),
    ]
