# Generated by Django 5.0.2 on 2024-09-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0010_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name_plural': 'Job Applications'},
        ),
    ]
