# Generated by Django 5.0.2 on 2024-03-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblisting', '0003_alter_job_languages_alter_job_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_new',
        ),
    ]
